### PR TITLE
testing allowing some time for processing event loop phases during atomicsWaitLoop

### PR DESCRIPTION
**Pull request by yakkomajuri**
just testing

this would give the event loop a bit of time to e.g. close sockets before `Atomics.wait` kicks back in

### CODE REVIEW

**Review by mariusandra — CHANGES_REQUESTED** [review]
I didn't test, but it seems there's a bug here that could cause problems. What happens if 5 sec pass, Atomics.wait returns and then the `sharedBuffer` is modified during the 100ms window that the `setTimeout` is waiting? Unless some event comes in one of the the next 5 sec wait windows, we would never look for new messages.

In principle this should do the trick, but I'd change the numbers a bit. I think the atomics can just wait `100ms`. When we're receiving 1 event per sec, we're idle anyway and can afford to check this 10 times. If we're receiving more than 10 events per sec, we'll never hit the limit and atomics will give the performance boost they give. Then I wouldn't  `setTimeout` it, but would instead actually run the function to the end, and only then `setImmediate` it to run again if no message was received.

**Comment by yakkomajuri** [comment]
So this was more for "demo" purposes, but that's not actually the case. If the buffer changes during the timeout period, the task will be read from the "slow" mechanism just as if `useAtomics = false`. There may be some more nuance from mixing these though.

**Comment by yakkomajuri** [comment]
Also I think `setImmediate` would be problematic in that it wouldn't allow the event loop to hit other phases?

**Comment by mariusandra** [comment]
Re: `setImmediate`, I'm always a bit confused, but replace that with "whatever is needed to flush the event loop" :).

**Comment by mariusandra** [comment]
Re: "that's not actually the case", even better! Give atomics 100ms quick-reaction time after each message, and then just revert to the slow loop that also helps clear buffers.

**Comment by yakkomajuri** [comment]
certainly needs some testing to confirm - will work some more on this tomorrow

**Comment by yakkomajuri** [comment]
Ok so here was my logic:

To benefit the most from `atomics`, let's add a timeout but keep coming back to it at an interval once the event loop has had time to process other callbacks. In this regard, calling it again at the end or using `setImmediate` wouldn't actually help, because as per the ordering of the event loop phases, the event loop would still be blocked as both of these approaches would cause it to run again before all the pending callbacks are processed. The goal was then to find sensible defaults, allowing enough time for atomics to work, and enough time for different types of callbacks to be processed (like running standard callbacks, closing sockets etc).

Ultimately, for now I'm going with the approach of "let's just make this configurable". Skipping the `setTimeout` and just letting atomics do its magic for a while before defaulting to the slower mechanism of waiting for the callback from the message on the port instead of proactively reading from it. This still needs to be benchmarked, but the good news is that making it configurable makes it easier to benchmark.

For us, it might make sense to set this to something like 1s on Cloud. However, when running locally or self-hosting, the current default of 5s might be more appropriate for better performance if you're not seeing huge volumes.

**Comment by yakkomajuri** [comment]
Also seems I need to write some tests :D

**Comment by yakkomajuri** [comment]
Although I guess if your workers are waiting 5+ seconds for new tasks, your setup for event ingestion probably doesn't need amazing performance at ingestion.

**Comment by yakkomajuri** [comment]
hmm might need to add in some sort of looping to account for a notification coming via `wait` but the thread not being the one that picks up the task

**Pull request closed without merging**
